### PR TITLE
Bug rival calculation

### LINKED ISSUE #89: Update `rival` and `favorite_opponent` to calculate based on win % vs num of wins
Doesn't impact our tests right now using fixture data, but these methods are calculated using just the num of wins/losses to a team. According to spec, they should be the name of the opponent with the _highest or lowest win percentage_ against a specific team. 

**To fix:**
- Make sure opponents_and_num_result_for_team return a key/value pair even if the opponent has not won any games against a team (ex: "5" => 0)
- Divide opponents_and_num_result_for_team by the num of games they have played against each opponent
- Take the max and min for rival and favorite_opponent

### PR DESCRIPTION
**Pull request by leahriffell**
**What was done to fix this bug:** 
- Make sure opponents_and_num_result_for_team return a key/value pair even if the opponent has not won any games against a team (ex: "5" => 0)
- Divide opponents_and_num_result_for_team by the num of games they have played against each opponent
- Take the max and min for rival and favorite_opponent

closes #89

### CODE REVIEW

**Review by sarynm12 — APPROVED** [review]

File: lib/stat_tracker.rb [hunk 1]
```diff
@@ -148,9 +148,10 @@ def game_result?(result, team_id, game_id)
     game.result == result
   end
 
-  def opponents_and_num_result_for_team(team_id, game_result)
+  def opponents_and_opponents_num_result_for_team(team_id, game_result)
     opponent_by_game_id_for_team(team_id).reduce(Hash.new(0)) do |result, game_id_oppo_ary|
-      result[game_id_oppo_ary[1]] += 1 if game_result?(game_result, team_id, game_id_oppo_ary[0])
+      result[game_id_oppo_ary[1]] += 0 
+      result[game_id_oppo_ary[1]] += 1 if game_result?(game_result, game_id_oppo_ary[1], game_id_oppo_ary[0])
```
Comment (AngelaGuardia) [inline lib/stat_tracker.rb:154]: Nice job here. I'm guessing the order here let you avoid an if/else statement right?

Comment (leahriffell) [reply lib/stat_tracker.rb:154]: yup exactly!

File: lib/stat_tracker.rb [hunk 2]
```diff
@@ -198,6 +199,16 @@ def percent_wins_by_coach(season_id)
     end
   end
 
+  def num_games_per_opponent_for_team(team_id)
+    opponent_by_game_id_for_team(team_id).each_with_object(Hash.new(0)) do |(game_id, team_id), result| 
+      result[team_id] += 1 if team_id == team_id 
+    end 
+  end
```
Comment (AngelaGuardia) [inline lib/stat_tracker.rb:206]: Nice! Is each_with_object like a better reduce for hashes?

**Review by AngelaGuardia — APPROVED** [review]

**Review by hopesgit — APPROVED** [review]

File: lib/stat_tracker.rb (hunk 2 above)
Comment (leahriffell) [reply lib/stat_tracker.rb:206]: I had been seeing some arguments online that each_with_object could be a better choice for hash transformations. I originally tried with .reduce but since I'm running the method on a hash, each_with_object seemed cleaner? Totally a matter of opinion I think but I do like how it doesn't reassign each time through and I don't have return result each time.
