### PR TITLE
IT2 - Team - team_info and most_goals_scored

### LINKED ISSUE #28: Team Stats - team info
Each of the methods below take a team id as an argument. Using that team id, your instance of StatTracker will provide statistics for a specific team.

Description:
A hash with key/value pairs for the following attributes: team_id, franchise_id, team_name, abbreviation, and link

Return:
Hash

### LINKED ISSUE #32: Team Stats - most_goals_scored
Each of the methods below take a team id as an argument. Using that team id, your instance of StatTracker will provide statistics for a specific team.

Description
Highest number of goals a particular team has scored in a single game.

Return
Integer

### LINKED ISSUE #58: RSpec - Percentage Bug
RSpec is failing because it expects percentage calculations to be in this format 0.43 as opposed to this format 43.33

### PR DESCRIPTION
**Pull request by AngelaGuardia**
**Changes made**
- Refactored all methods and tests that calculate percentages to meet Spec harness format

**Helper Methods**
- _find_team_ - takes a team id and returns a team object
- _goals_per_game_per_team_ - returns a hash if team ids to an array of goals scored
- ^ this method will help with _fewest_goals_scored_ @hopesgit 

**Team Methods**
- _team_info_
- _most_goals_scored_

### CODE REVIEW

File: test/stat_tracker_test.rb [hunk 1]
```diff
@@ -209,4 +232,23 @@ def test_it_can_find_the_worst_offensive_team
...
+
+  def test_it_gets_team_info
+    expected = {
+                id: 3,
+                franchise_id: 10,
+                name: "Houston Dynamo",
+                abbreviation: "HOU",
+                link: "/api/v1/teams/3"
+                }
+
```
Comment (leahriffell) [inline test/stat_tracker_test.rb:244]: @guardiac not sure if this matters, but the spec asks for `team_id` and `team_name` instead of just `id` and `name`.

File: lib/stat_tracker.rb [hunk 2]
```diff
@@ -169,4 +180,22 @@ def lowest_scoring_home_team
...
+      name: team.name,
+      abbreviation: team.abbreviation,
+      link: team.link
+    }
+  end
+
+  def most_goals_scored(team_id)
+     goals_p_game_p_team_hash = goals_per_game_per_team
+     goals_p_game_p_team_hash[team_id].max
+  end
```
Comment (leahriffell) [inline lib/stat_tracker.rb:199]: Could this one just be `goals_per_game_per_team[team_id].max`? Instead of having to set it equal to a local variable?

Comment (AngelaGuardia) [reply lib/stat_tracker.rb:199]: You're right! I just updated it.

File: test/stat_tracker_test.rb [hunk 3]
```diff
@@ -127,6 +127,29 @@ def test_it_can_get_average_goals_per_game_per_team_hoa
     assert_equal expected_avg_away_goals_p_game_p_team, @@stat_tracker.average_goals_per_game_per_team(exclude)
   end
 
+  def test_it_can_find_a_team
+    team3 = @@stat_tracker.teams.find { |team| team.id == 3 }
+
+    assert_equal team3, @@stat_tracker.find_team(3)
+  end
+
```
Comment (leahriffell) [inline test/stat_tracker_test.rb:133]: Since the .find_team method also uses `teams.find { |team| team.id == team_id }` isn't this kind of like asserting equal to itself? Maybe instead of creating a variable to assert to, you could `assert_equal 10, @@stat_tracker.find_team(3).franchise_id` or something like that?

**Review by leahriffell — COMMENTED** [review]
Thank you for fixing all of the percent formatting, @guardiac!!

File: test/stat_tracker_test.rb (hunk 3 above)
Comment (AngelaGuardia) [reply test/stat_tracker_test.rb:133]: Yesss!! That's such a simple solution. I didn't feel great about this test so thank you. It's updated now.

**Review by leahriffell — APPROVED** [review]
Looks great, thank you!!

File: lib/stat_tracker.rb [hunk 4]
```diff
@@ -104,15 +115,15 @@ def lowest_total_score
...
   end
 
   def percentage_home_wins
-    ((total_home_wins / total_games.to_f) * 100).round(2)
+    (total_home_wins / total_games.to_f).round(2)
   end
 
   def percentage_ties
-    ((total_tied_games / total_games.to_f) * 100).round(2)
+    (total_tied_games / total_games.to_f).round(2)
```
Comment (sarynm12) [inline lib/stat_tracker.rb:126]: Thanks for fixing these to match the spec harness :)

**Review by sarynm12 — APPROVED** [review]
Thanks for making these changes, Angela

**Review by hopesgit — APPROVED** [review]
